## Johnatan Meoño

In [1]:
import numpy as np

### Investigacion No. 4
### Diferencias entre np.matrix y np.ndarray  



### np.matrix

De las notas de clase podemos decri que: Una matriz es un arreglo multidimensional de filas y columnas. La matriz es una estructura mas general. Esta contiene muchas observaciones que poseen mas de una característica.

En NumPy las matrices son(de manera similar a los vectores) objetos del tipo **np.ndarray**, la diferencia es la forma en que estos estan organizados y por lo tanto ciertas características de los mismos.

La matriz es un tensor de rango dos, es decir para acceder a uno de sus valores se necesitan de dos posiciones para extraerlo, en este caso fila y columna. 

* np.matrix: resultado casi identico a la función mas general np.array ,pero posee algunas propiedades adicionales específicas de listas, por ejemplo notación sencilla para inversas de matrices.

In [21]:
matrix1 = np.matrix([[1,2,3,4],
                     [5,6,7,8]])
print(matrix1)
print(type(matrix1))
print(matrix1.ndim)
print(matrix1.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.matrixlib.defmatrix.matrix'>
2
(2, 4)


In [22]:
matrix2 = np.matrix([[1,2,3,4]])

print(matrix2)
print(type(matrix2))
print(matrix2.ndim)
print(matrix2.shape)

[[1 2 3 4]]
<class 'numpy.matrixlib.defmatrix.matrix'>
2
(1, 4)


### En este ejemplo definimos una matriz que solo tiene un valor, cuando vemos sus propiedades es de clase numpy.matrixlib.defmatrix.matrix, sigue teniendo rango dos a pesar de solo tener un valor, y su forma es una fila y una columna. 

In [26]:
matrixn = np.matrix([[1]])

print(matrixn)
print(type(matrixn))
print(matrixn.ndim)
print(matrixn.shape)

[[1]]
<class 'numpy.matrixlib.defmatrix.matrix'>
2
(1, 1)



### np.ndarray  

De las notas de clase sabemos que: Matemáticamente el Tensor es la entidad mas general cuando hablamos de arreglos o colecciones de elementos y que comunmente representan coordenadas en un plano posiblemente multidimensional, por lo tanto al traducirlo a software científico un tensor es también la estructura mas general para trabajar ,y es la estructura de datos básica en la cual almacenaremos información, **NumPy logra esto a través del objeto ndarray**(tensorflow usa tf.Tensor, PyTorch usa  torch.Tensor).

En este caso los objetos que pertenecen a la clase ndarray son aquellos que podemos definir con las funciones ya conocidas por ejemplo np.arange ó np.array, solo que al definir un objeto de este tipo podemos estar definidendo un vector de rango uno o una matriz de rango dos.

Es decir partimos de las clases ndarray y podemos definir una matriz, que tendra rango dos, no obstante su clase sera siempre ndarray.

Sin embargo como vimos arriba cuando definimos una matriz con np.matrix su clase siempre sera numpy.matrixlib.defmatrix.matrix, y tendra rango dos. 

Vemos que al aplicar shape sobre este arreglo devuelve la cantidad de elementos del arreglo


In [23]:
array1 = np.arange(10)
print(array1)
print(type(array1))
print(array1.ndim)
print(array1.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)


### Definimos una matriz a partir de np.array el cual es una clase numpy.ndarray, si obtendremos su rango dos, pero su clase no es la misma si la definimos desde np.array 

### Como podemos observar cuando consultamos la forma de este arreglo generado desde np.array, nos devuelve una tupla con el número de filas y columnas

* np.array: crear una matriz a partir de una lista de listas: cada fila es una sublista

In [24]:
matrix3 = np.array([[0.,  0.,  0.,  0.],
                   [0.,  0.,  0.,  0.],
                   [0.,  0.,  0.,  0.]])
print(matrix3)
print(type(matrix3))
print(matrix3.ndim)
print(matrix3.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
2
(3, 4)
