## Johntan Meoño

## Ejercicio 1



**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresion.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = numero de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [3]:
import numpy as np

In [4]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

multi = gamma * P
productomatri = np.matmul(multi,V)

print(productomatri)

Vfinal = R+productomatri

print(Vfinal)

[0. 0. 0.]
[10.  2.  5.]


## Ejemplo 2

In [6]:
## asi se calcula la fucion 
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [7]:
## asi se calcula la fucion 
def relu(m): 
    valor = np.piecewise(m, [m < 0,m >= 0], 
                                [lambda m: 0,
                                 lambda m: m])
    return valor 

        
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

x = np.array([[1,1]])

intermedia = np.array([[0.712,0.355,0.268],
                       [0.112,0.855,0.468]])

final = np.array([[0.116],
                  [0.329],
                  [0.708]])

print(x)
print(x.shape)

print("Neurona inicial",
      X)
print(X.shape)

print("capa intermedia",
      intermedia)

paso1 = np.matmul(X,intermedia)
paso1 = sigmoid(paso1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

print("Neurona intermedia",
      paso1)

print("capa final",
      final)

paso2 = np.matmul(paso1,final)
paso2 = relu(paso2)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

print("Neurona final",
      paso2)

[[1 1]]
(1, 2)
Neurona inicial [[1.0e-01 2.0e+00]
 [3.0e-01 4.5e-01]
 [5.0e+00 9.0e+00]
 [1.2e+01 6.0e+00]
 [7.0e+00 5.0e+00]
 [3.0e-01 8.0e-01]
 [1.2e+01 5.0e+00]
 [1.0e+02 2.0e+02]
 [7.0e+00 8.0e+00]
 [3.0e+02 1.5e+03]]
(10, 2)
capa intermedia [[0.712 0.355 0.268]
 [0.112 0.855 0.468]]
Neurona intermedia [[0.5732687  0.85138432 0.72368206]
 [0.56561932 0.62040086 0.57224093]
 [0.98972791 0.99992287 0.9961353 ]
 [0.99990057 0.99991645 0.99758587]
 [0.99610438 0.99884211 0.98545706]
 [0.5752246  0.68793868 0.61177987]
 [0.99988879 0.99980357 0.99615067]
 [1.         1.         1.        ]
 [0.997213   0.99991084 0.99638845]
 [1.         1.         1.        ]]
capa final [[0.116]
 [0.329]
 [0.708]]
Neurona final [[0.85897151]
 [0.6748703 ]
 [1.14904686]
 [1.15125178]
 [1.14187076]
 [0.72619803]
 [1.15019715]
 [1.153     ]
 [1.1500904 ]
 [1.153     ]]
